vcenters:
  - displayName: "vCenter Production"
    host: "10.0.0.1"
    username: "admin"
    password: "password"

controllers:
  - displayName: "Controller Production"
    controllerHost: "https://xxxx.saas.appdynamics.com"
    clientId: "abc@def"
    clientSecret: "1895e99f-aa84-26cf-65d0-319403a1b4be"
    proxyHost:
    proxyPort:
    proxySsl:

numberOfThreads: 30
metricPrefix: "Custom Metrics|VMWare-TAG|"
encryptionKey: ""

#date format in tags
formatDate: dd/MM/yyyy HH:mm:ss

# publish host metrics
publishMetrics: true

# waiting time between API calls
sleepTime: 2500

# total number of tags to be published in each api call
totalTagsByCall: 50

# additional name of the Machine Agent that needs to be removed to search for the server name in the VMWare API, necessary because some customers put the domain in the MA name but vCenter does not do this
removeDomainName:
  - domain: .devices.company.com.br
