vcenters:
  - displayName: "vCenter Production"
    host: "10.0.0.1"
    username: "admin"
    password: "password"

controllers:
  - displayName: "Controller Production"
    controllerHost: "https://xxxx.saas.appdynamics.com"
    clientId: "abc@def"
    clientSecret: "1895e99f-aa84-26cf-65d0-319403a1b4be"
    proxyHost:
    proxyPort:
    proxySsl:

numberOfThreads: 30
metricPrefix: "Custom Metrics|VMWareTag"
encryptionKey: ""
frequency: 120000
formatDate: dd/MM/yyyy HH:mm:ss
publishMetrics: true
